### PR TITLE
Added UnifyUniques setting

### PR DESCRIPTION
**Pull request by ChaosMarc**
This time a clean implementation. you're absolutely right. my first attempt was absolutely "hacky"

I'm a bit confused why you removed (and ignored) the settings.ini, though

### CODE REVIEW

**Review by mrpara — APPROVED** [review]
I'll do some refactoring myself, but this is fine. 
Thanks!

**Comment by mrpara** [comment]
Sorry, had some mixups with the files while trying some things (hence the settings bit).
I've merged your PR, but I changed it from unifying on item code to item type. I think having different pages for unique shields, axes, etc, is great - but I don't see the reason for having one for each item code. I thought that's what you'd meant from the beginning, honestly. Sorry

**Comment by ChaosMarc** [comment]
I have my stash organized with each different unique on a new page. would you be open to a PR where i make it configurable on what to split the pages for uniques (code vs type)? I'm also working on parsing the advanced item stats for more advanced sorting, but this will take some time

**Comment by mrpara** [comment]
No, I would not be open to either PR. I want to keep this as simple as it could be. As I said I am actually considering eliminating both "unify" options and making them both =0 by default. Allowing too much user customization and advanced parsing takes this out of the originally planned scope, and will make it grow beyond what is easily changable or maintanable. I do not object to minor additions (sorting by item picture, etc) however. 
You are of course more than welcome to simply fork the code, and if you have any questions or need advice on how to change things I'll be happy to help.

**Comment by ChaosMarc** [comment]
ok. I can respect that. if that's the case I will only implement in my fork but will try to integrate your upstream changes

**Pull request merged**
